#!/usr/bin/env bash
# configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sed '0 a/ > frontend haproxy-main\bind *:80\option forwardfor\default_backend apache_webservers\backend apache_webservers\balance roundrobin\server websvr1	34.74.125.65:80 check\server websvr2	35.196.84.183:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
