#!/usr/bin/env bash
# configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sed '0 a/ > frontend haproxy-main\bind *:80\option forwardfor\default_backend apache_webservers\backend apache_webservers\balance roundrobin\server 3796-web-01	34.74.125.65:80 check\server 3796-web-02    35.196.84.183:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
