#!/usr/bin/env bash
# This script Creates the file /var/run/myscript.pid containing its PID
file="/var/run/myscript.pid"
sudo touch $file
sudo bash -c 'echo $BASHPID > $file'
for ((;;)); do 
echo "To infinity and beyond" ; sleep 2;
trap 'echo "I hate the kill command"; sudo rm $file; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap  'sudo rm $file; exit' SIGQUIT SIGTERM 
done
