#!/usr/bin/env bash
# This script is displays numbers from 1 to 100.
i=1
while [ $i -lt 101 ]
do
	if [ $(( i % 15 )) -eq 0 ]
	then
		echo "Fizzbuzz"
	elif [ $(( i % 3 )) -eq 0 ]
	then
		echo "Fizz"
	elif [ $(( i % 5 )) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$(( i + 1 ))
done
