#!/usr/bin/env bash
# This script is displaying "Best School" 8 times displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration
i=1
while [ $i -lt 11 ]
do
	if [ $i -lt 4 ]
	then
		echo "Best School"
	elif [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -gt 4 ] && [ $i -lt 8 ]
	then
		echo "Best School"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
