#!/usr/bin/env bash
# This script gives you information about the school file.
if [ -e school ]
then
	echo "school file exists"
	if [ -f school ]
	then
		echo "school is a regular file"
	elif [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
