#!/usr/bin/env bash
# This Bash script that configures an Ubuntu server
cp /etc/hosts ~/localhost
sed -i s/127.0.0.2// ~/localhost
cp -f ~/localhost /etc/hosts
cp /etc/hosts ~/facebook.com
sed -i s/8.8.8.8// ~/facebook.com
cp -f ~/facebook.com /etc/hosts
